services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ${UMBREL_ROOT}/home/Documents/Glance/:/app/config
    ports:
      - 8081:8080
networks: {}
