services:
  mc:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    environment:
      VERSION: b1.7.3
      DISABLE_HEALTHCHECK: true
      EULA: TRUE
      SERVER_NAME: "Umbrel"
      MOTD: "Your Umbrel Minecraft server."
    volumes:
      - ./world:/data
    restart: unless-stopped
volumes:
  mc: {}