services:
  minecraft:
    image: itzg/minecraft-server
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    environment:
      MAX_MEMORY: 1G
      VERSION: "b1.7.3"
      EULA: "TRUE"
    restart: unless-stopped