services:
  minecraft:
    image: itzg/minecraft-server
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    environment:
      TYPE: CUSTOM

      MAX_MEMORY: 1G
      VERSION: b1.7.3
      CUSTOM_SERVER: "https://files.betacraft.uk/server-archive/beta/b1.7.3.jar"
      EULA: "TRUE"
    restart: unless-stopped