services:
  mc:
    image: itzg/minecraft-server
    container_name: paper
    environment:
      EULA: "true"
      ENABLE_AUTOPAUSE: "true"
      MAX_PLAYERS: 5
      CREATE_CONSOLE_IN_PIPE: "true"
      SERVER_NAME: "Umbrel server"
      SNOOPER_ENABLED: "false"
      DIFFICULTY: "peaceful"
      TYPE: PAPER
      VIEW_DISTANCE: 12
      SIMULATION_DISTANCE: "5"
      MEMORY: 2G
    ports:
      - "25565:25565"
    volumes:
      - mc-paper:/data
    restart: unless-stopped
volumes:
  mc-paper: {}