name: crafty
# Base file from https://gitlab.com/crafty-controller/crafty-4/-/blob/dev/docker/docker-compose.yml
version: "3"

services:
  crafty:
    container_name: crafty-container
    image: registry.gitlab.com/crafty-controller/crafty-4:4.4.4
    restart: always
    environment:
      - TZ=Etc/UTC
    ports:
      - "8111:8443" # HTTPS
      - "8112:8123" # DYNMAP
      - "19132:19132/udp" # BEDROCK
      - "25500-25600:25500-25600" # MC SERVER PORT RANGE
    volumes:
      - /DATA/AppData/crafty/backups:/crafty/backups
      - /DATA/AppData/crafty/logs:/crafty/logs
      - /DATA/AppData/crafty/servers:/crafty/servers
      - /DATA/AppData/crafty/config:/crafty/app/config
      - /DATA/AppData/crafty/import:/crafty/import

    x-casaos:
      ports:
        - container: "19132"
          description:
            en_us: Minecraft Bedrock listening Port (UDP)
            zh_cn: Minecraft Bedrock监听端口 (UDP)
          protocol: udp

        - container: "25565"
          description:
            en_us: Minecraft listening Port (TCP)
            zh_cn: Minecraft监听端口 (TCP)
          protocol: tcp

        - container: "25566"
          description:
            en_us: Minecraft listening Port (TCP)
            zh_cn: Minecraft监听端口 (TCP)
          protocol: tcp

        - container: "25567"
          description:
            en_us: Minecraft listening Port (TCP)
            zh_cn: Minecraft监听端口 (TCP)
          protocol: tcp

        - container: "25568"
          description:
            en_us: Minecraft listening Port (TCP)
            zh_cn: Minecraft监听端口 (TCP)
          protocol: tcp

        - container: "25569"
          description:
            en_us: Minecraft listening Port (TCP)
            zh_cn: Minecraft监听端口 (TCP)
          protocol: tcp

        - container: "25570"
          description:
            en_us: Minecraft listening Port (TCP)
            zh_cn: Minecraft监听端口 (TCP)
          protocol: tcp

        - container: "25565"
          description:
            en_us: Minecraft listening Port (UDP)
            zh_cn: Minecraft监听端口 (UDP)
          protocol: udp

        - container: "25566"
          description:
            en_us: Minecraft listening Port (UDP)
            zh_cn: Minecraft监听端口 (UDP)
          protocol: udp

        - container: "25567"
          description:
            en_us: Minecraft listening Port (UDP)
            zh_cn: Minecraft监听端口 (UDP)
          protocol: udp

        - container: "25568"
          description:
            en_us: Minecraft listening Port (UDP)
            zh_cn: Minecraft监听端口 (UDP)
          protocol: udp

        - container: "25569"
          description:
            en_us: Minecraft listening Port (UDP)
            zh_cn: Minecraft监听端口 (UDP)
          protocol: udp

        - container: "25570"
          description:
            en_us: Minecraft listening Port (UDP)
            zh_cn: Minecraft监听端口 (UDP)
          protocol: udp
