name: linuxserver-kasm
services:
  app:
    image: linuxserver/kasm:1.16.1
    restart: unless-stopped
    environment:
      KASM_PORT: ''
      DOCKER_HUB_USERNAME: ''
      DOCKER_HUB_PASSWORD: ''
      DOCKER_MTU: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/kasm/opt
        target: /opt
      - type: bind
        source: /DATA/AppData/kasm/profiles
        target: /profiles
      - type: bind
        source: /dev/input
        target: /dev/input
      - type: bind
        source: /run/udev/data
        target: /run/udev/data