version: "3.5"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      NEXTAUTH_URL: http://localhost:3000/api/v1/auth
      NEXTAUTH_SECRET: wz3pwfqYStS@8GaTEoOU
      POSTGRES_PASSWORD: W@z122AsjHVdrW0tk^8A
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    # build: . # uncomment this line to build from source
    image: ghcr.io/linkwarden/linkwarden:latest # comment this line to build from source
    ports:
      - 3000:3000
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
