version: '3.5'

services:
  postgres:
    image: postgres:16-alpine
    restart: on-failure
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: W@z122AsjHVdrW0tk^8A
      POSTGRES_DB: postgres
    networks:
      - linkwarden-network

  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest # comment this line to build from source
    restart: on-failure
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://postgres:W@z122AsjHVdrW0tk^8A@postgres:5432/postgres
      NEXTAUTH_URL: http://localhost:3000/api/v1/auth
      NEXTAUTH_SECRET: wz3pwfqYStS@8GaTEoOU
      POSTGRES_PASSWORD: W@z122AsjHVdrW0tk^8A
    volumes:
      - ./data:/data/data
    depends_on:
      - postgres
    networks:
      - linkwarden-network

networks:
  linkwarden-network:
    driver: bridge
